services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: iot_data
      MYSQL_USER: iotuser
      MYSQL_PASSWORD: iotpass
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql

  bridge:
    build: ./bridge
    container_name: mqtt_bridge
    depends_on:
      - mosquitto
      - mariadb
    environment:
      MQTT_BROKER: mosquitto
      MQTT_TOPIC: esp32/data
      DB_HOST: mariadb
      DB_USER: iotuser
      DB_PASSWORD: iotpass
      DB_NAME: iot_data

  laravel-app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: iot_data
      DB_USERNAME: iotuser
      DB_PASSWORD: iotpass
      
  laravel-web:
    image: nginx:latest
    container_name: laravel-web
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
